version: "3.9"
services:
  bakery-gateway:
    container_name: gateway
    depends_on:
      - "bakery-front"
      - "workbench-front"
      - "bakery-back"
    image: cruibakeryonprem.azurecr.io/cloud/gateway:aci-2.28.1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
    ports:
      - "80:80"

  bakery-front:
    container_name: bakery-front
    image: cruibakeryonprem.azurecr.io/cloud/bakery-front:aci-2.28.1
    restart: always
    environment:
      - UI_BAKERY_APP_SERVER_NAME=https://123.123.123.123:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "3030:3030"

  workbench-front:
    container_name: workbench-front
    image: cruibakeryonprem.azurecr.io/cloud/workbench-front:aci-2.28.1
    restart: always
    environment:
      - UI_BAKERY_APP_SERVER_NAME=https://123.123.123.123:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "3040:3040"

  datasource:
    container_name: datasource
    image: cruibakeryonprem.azurecr.io/cloud/datasource:2.28.1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    ports:
      - "6060:6060"

  bakery-back:
    container_name: bakery-back
    image: cruibakeryonprem.azurecr.io/cloud/bakery-back:2.28.1
    restart: always
    environment:
      - UI_BAKERY_LICENSE_KEY=${UI_BAKERY_LICENSE_KEY:-PUT_LICENCE_HERE}
      - UI_BAKERY_DB_HOST=${UI_BAKERY_DB_HOST:-azure-container-instance-test-db.mysql.database.azure.com}
      - UI_BAKERY_DB_PORT=${UI_BAKERY_DB_PORT:-3306}
      - UI_BAKERY_DB_DATABASE=${UI_BAKERY_DB_DATABASE:-bakery}
      - UI_BAKERY_DB_USERNAME=${UI_BAKERY_DB_USERNAME:-uibakeryuser@azure-container-instance-db}
      - UI_BAKERY_DB_PASSWORD=${UI_BAKERY_DB_PASSWORD:-uibakerypassword}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    ports:
      - "8080:8080"

  automation:
    container_name: automation
    image: cruibakeryonprem.azurecr.io/cloud/automation:2.28.1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    ports:
      - "4000:4000"
